AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Static Website Hosting using CloudFormation

Resources:

  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-static-website-bucket-12-25-2025
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  StaticWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticWebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource:
              - !Sub "${StaticWebsiteBucket.Arn}/*"

Outputs:

  WebsiteURL:
    Description: S3 Static Website URL
    Value: !GetAtt StaticWebsiteBucket.WebsiteURL
